sonar update
splitio/ios-client pull request #310
Opened 2021-12-22 18:05 UTC by LucianoCaravajal

# iOS SDK

## What did you accomplish?

## How do we test the changes introduced in this PR?

## Extra Notes

2021-12-22 18:10 UTC, javrudsky approved these changes
LGTM!

2021-12-22 18:26 UTC, melinaurruchua commented on .github/workflows/sonar.yml
> +            -Dsonar.pullrequest.base=${{ github.event.pull_request.base.ref }}
end line is missing

2021-12-22 18:26 UTC, melinaurruchua commented on .github/workflows/sonar.yml
> +      - name: SonarQube Scan
can you let a line between the different steps?

2021-12-22 18:26 UTC, melinaurruchua commented on .github/workflows/sonar.yml
> +      - uses: actions/checkout@v2
can you add a name?

2021-12-22 21:17 UTC, Israphel commented
without the build, you won't have coverage info

2021-12-22 21:18 UTC, Israphel commented
sonar has to run for PRs and merges (with different parameters)

2022-01-04 20:52 UTC, Israphel commented
why not running everything in the same workflow if you have to build anyway?

2022-01-05 14:57 UTC, Israphel requested changes
sonarqube requires two kinds of executions with differente parameters.

if the build will be repeated, then combine the workflows.

2022-01-06 20:40 UTC, merged