Semver class implementation
splitio/ios-client pull request #523
Opened 2024-05-13 14:49 UTC by gthea

# iOS SDK

## What did you accomplish?

- Added implementation for semver class.

2024-05-13 15:32 UTC, EmilianoSanchez approved these changes

2024-05-13 18:31 UTC, javrudsky requested changes

2024-05-13 18:31 UTC, javrudsky commented on Split/Matchers/Semver/Semver.swift
> +            guard metadataIndex < version.endIndex else {
I wouldn't use guard when no unwrapping an optional, because I think is confusing. But this is a personal opinion.

2024-05-13 18:31 UTC, javrudsky commented on Split/Matchers/Semver/Semver.swift
> +        var vWithoutPreRelease = ""
Same here. Maybe applying the first comment.

2024-05-13 18:31 UTC, javrudsky commented on Split/Matchers/Semver/Semver.swift
> +            let metadataString = String(version[metadataIndex...])
Here, maybe you can do something like:
```
   // Create this function
   func buildMedatag(version) throws -> String {
            let metadata = String(version[metadataIndex...])
            if metadata.isEmpty {
                throw SemverParseError.invalidVersionFormat("Unable to convert to Semver, incorrect metadata")
            }
            return metadata
     }
```
Then in the init function

```
     let metadata = try buildMetadata(version: version)
```

2024-05-14 15:19 UTC, javrudsky requested changes
Good job! Just some comments.

2024-05-14 15:19 UTC, javrudsky commented on Split/Matchers/Semver/Semver.swift
> +    private var major: Int64 = -1
How about replacing this values by a struct like:
```
struct SemverModel {
let major: Int64
let minor: Int64
let patch: Int64
...
}

2024-05-14 15:19 UTC, javrudsky commented on Split/Matchers/Semver/Semver.swift
>      private func setVersion() -> String {
This could be a function `toString()` from SemverModel

2024-05-14 15:19 UTC, javrudsky commented on Split/Matchers/Semver/Semver.swift
> +    private func getMajorMinorAndPatch(_ vWithoutPreRelease: String) throws -> (major: Int64, minor: Int64, patch: Int64) {
`func baseVersion(withoutPreRelease: String) -> SemverModel {`
Also please use named parameters. It makes the code self descriptive.

2024-05-14 15:19 UTC, javrudsky commented on Split/Matchers/Semver/Semver.swift
> +    private func getAndRemovePreReleaseIfExists(_ vWithoutMetadata: String) throws -> (preRelease: [String], isStable: Bool, versionWithoutPreRelease: String) {
Maybe you can use the model here too:
`func versionWithoutPreRelease(withoutMetaData: String) throws -> SemverModel {`

2024-05-14 19:38 UTC, merged